# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15XdUf6ly5brwHxBYLbEEYDHergBIRHCD
"""

# aula2

# execicio1
largura = 17
altura = 12
delimitador = '.'

print(largura/2)
print(type(largura/2))

print(largura/2.0)
print(type(largura/2.0))

print(altura/3)
print(type(altura/3))

print(1+2*5)
print(type(1+2*5))

print(delimitador*5)
print(type(delimitador*5))

#exercicio2
import math

r = 5
v = (3/4)*math.pi*r**3

print('O volume da esfera é: ', v)

#exercicio3
valor_livro = 24.95
valor_desconto = 40/100
valor_primeira_entrega = 3
valor_entrega_adicional = 0.75
quantidade_livros = 60
valor_compra = ((valor_livro*(1-valor_desconto))*quantidade_livros + valor_primeira_entrega + (quantidade_livros-1)*valor_entrega_adicional)

print('O valor da sua compra foi de: ', valor_compra)

#exercicio4
comprimento_de_onda = 632.8 * 10**(-9)
distancia_do_layser_ao_anteparo = 1.98
espacameno_entre_as_fendas = 0.25 * 10**(-3)
delta_y = (comprimento_de_onda) * (distancia_do_layser_ao_anteparo/espacameno_entre_as_fendas)

print(delta_y)